project:
  type: website
  preview: 
    port: 1234

website:
  title: "Nicolas' Notebook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nbrosse
      - icon: linkedin
        href: https://www.linkedin.com/in/nicolas-brosse-984685a0/
      - icon: google
        href: https://scholar.google.com/citations?user=sQ6d5AYAAAAJ&hl
      - icon: r-circle
        href: https://www.researchgate.net/profile/Nicolas-Brosse-3
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

theme:
  light: flatly
  dark: darkly


